# .sops.yaml
creation_rules:
  # Secrets shared across all machines
  - path_regex: secrets/shared\.env$
    age: age134m4v3nw4u54nt63wy9hkn08ls08teeah0fnw8w3cduuy2ns7qwq2faxyd,age1c5stkppwcpet70gg6a6xz6ep4wc90uwur6qdfynk00jay794ed0swcq667,age1g8dxh5x06pv224e8vwvazq8ra9dxetz0xrmeccpd5yfkpsaqquvq3rahzw
